# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainUI_Ver_2.ui'
#
# Created: Tue Jan 15 16:46:53 2019
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1302, 590)
        MainWindow.setMinimumSize(QtCore.QSize(886, 590))
        MainWindow.setStyleSheet("QFrame{\n"
"    background-color: #EEEEEE;\n"
"}\n"
"QPushButton{\n"
"    background-color:     #CCCCCC;\n"
"    color: rgb(0, 0, 0);\n"
"    font: 75 14pt \"Times New Roman\";\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: #0078D4;\n"
"    color: rgb(255, 255, 255);\n"
"    font: 14pt \"Calibri\";\n"
"}\n"
"QPushButton:checked{\n"
"    color: #AAAAAA;\n"
"}\n"
"QLabel{\n"
"    color: rgb(0, 0, 0);\n"
"background-color: #EEEEEE;\n"
"    font: 75 14pt \"Calibri\";\n"
"}\n"
"QComboBox{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: #FFFFFF;\n"
"    font: 14pt \"Calibri\";\n"
"}\n"
"QGroupBox{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: #EEEEEE;\n"
"    font: 75 14pt \"Calibri\";\n"
"    border: 1px solid black;\n"
"    margin-top: 3ex;\n"
"}\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top left; /* position at the top center */\n"
"    padding: 0 3px;\n"
"}\n"
"QRadioButton{\n"
"    color:rgb(0,0,0);\n"
"}\n"
"QRadioButton::indicator{\n"
"    width: 13px;\n"
"    height: 13px;\n"
"}\n"
"QRadioButton::indicator:checked:hover {\n"
"    color: #C7CCD7;\n"
"}\n"
"QTextEdit{\n"
"    background-color: #FFFFFF;\n"
"    color: rgb(0, 0, 0);\n"
"    border-width: 2px;\n"
"    border-color: rgb(0, 0, 0);\n"
"}\n"
"QLineEdit{\n"
"    background-color: #FFFFFF;\n"
"    color: rgb(0, 0, 0);\n"
"    border-width: 2px;\n"
"    border-color: rgb(0, 0, 0);\n"
"}\n"
"QLineEdit:hover{\n"
"    border: 1px solid blue; \n"
"    background-color: #FFFFFF;\n"
"}\n"
"QDoubleSpinBox{\n"
"color: rgb(255, 255, 255);\n"
"background-color: #C7CCD7;\n"
"}\n"
"QDoubleSpinBox:hover{\n"
"background-color: #C7CCD7;\n"
"}")
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout_5.setContentsMargins(9, 0, -1, -1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtGui.QGroupBox(self.frame)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setWeight(9)
        font.setItalic(False)
        font.setBold(False)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.connect_btn = QtGui.QPushButton(self.groupBox)
        self.connect_btn.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setWeight(9)
        font.setItalic(False)
        font.setBold(False)
        self.connect_btn.setFont(font)
        self.connect_btn.setCheckable(True)
        self.connect_btn.setObjectName("connect_btn")
        self.verticalLayout_2.addWidget(self.connect_btn)
        self.rescan_btn = QtGui.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setWeight(9)
        font.setItalic(False)
        font.setBold(False)
        self.rescan_btn.setFont(font)
        self.rescan_btn.setObjectName("rescan_btn")
        self.verticalLayout_2.addWidget(self.rescan_btn)
        self.show_about_btn = QtGui.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setWeight(9)
        font.setItalic(False)
        font.setBold(False)
        self.show_about_btn.setFont(font)
        self.show_about_btn.setObjectName("show_about_btn")
        self.verticalLayout_2.addWidget(self.show_about_btn)
        self.exit_btn = QtGui.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setWeight(9)
        font.setItalic(False)
        font.setBold(False)
        self.exit_btn.setFont(font)
        self.exit_btn.setObjectName("exit_btn")
        self.verticalLayout_2.addWidget(self.exit_btn)
        self.horizontalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.frame)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setWeight(9)
        font.setItalic(False)
        font.setBold(False)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.comport_combobox = QtGui.QComboBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.comport_combobox.setFont(font)
        self.comport_combobox.setObjectName("comport_combobox")
        self.verticalLayout_3.addWidget(self.comport_combobox)
        self.rate9600_rbtn = QtGui.QRadioButton(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.rate9600_rbtn.setFont(font)
        self.rate9600_rbtn.setObjectName("rate9600_rbtn")
        self.verticalLayout_3.addWidget(self.rate9600_rbtn)
        self.rate19200_rbtn = QtGui.QRadioButton(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.rate19200_rbtn.setFont(font)
        self.rate19200_rbtn.setObjectName("rate19200_rbtn")
        self.verticalLayout_3.addWidget(self.rate19200_rbtn)
        self.rate115200_rbtn = QtGui.QRadioButton(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.rate115200_rbtn.setFont(font)
        self.rate115200_rbtn.setChecked(True)
        self.rate115200_rbtn.setObjectName("rate115200_rbtn")
        self.verticalLayout_3.addWidget(self.rate115200_rbtn)
        self.horizontalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtGui.QGroupBox(self.frame)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setWeight(9)
        font.setItalic(False)
        font.setBold(False)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.set_marco_btn = QtGui.QPushButton(self.groupBox_3)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setWeight(9)
        font.setItalic(False)
        font.setBold(False)
        self.set_marco_btn.setFont(font)
        self.set_marco_btn.setObjectName("set_marco_btn")
        self.verticalLayout_4.addWidget(self.set_marco_btn)
        self.open_marco_file_btn = QtGui.QPushButton(self.groupBox_3)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setWeight(9)
        font.setItalic(False)
        font.setBold(False)
        self.open_marco_file_btn.setFont(font)
        self.open_marco_file_btn.setObjectName("open_marco_file_btn")
        self.verticalLayout_4.addWidget(self.open_marco_file_btn)
        self.save_marco_file_btn = QtGui.QPushButton(self.groupBox_3)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setWeight(9)
        font.setItalic(False)
        font.setBold(False)
        self.save_marco_file_btn.setFont(font)
        self.save_marco_file_btn.setObjectName("save_marco_file_btn")
        self.verticalLayout_4.addWidget(self.save_marco_file_btn)
        self.show_ascii_btn = QtGui.QPushButton(self.groupBox_3)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setWeight(9)
        font.setItalic(False)
        font.setBold(False)
        self.show_ascii_btn.setFont(font)
        self.show_ascii_btn.setObjectName("show_ascii_btn")
        self.verticalLayout_4.addWidget(self.show_ascii_btn)
        self.horizontalLayout.addWidget(self.groupBox_3)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.horizontalLayout.setStretch(0, 4)
        self.horizontalLayout.setStretch(1, 4)
        self.horizontalLayout.setStretch(2, 3)
        self.horizontalLayout.setStretch(3, 20)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.send_string_lineedit = QtGui.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(14)
        self.send_string_lineedit.setFont(font)
        self.send_string_lineedit.setObjectName("send_string_lineedit")
        self.gridLayout_2.addWidget(self.send_string_lineedit, 1, 0, 1, 1)
        self.display_chg_btn = QtGui.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setWeight(9)
        font.setItalic(False)
        font.setBold(False)
        self.display_chg_btn.setFont(font)
        self.display_chg_btn.setWhatsThis("")
        self.display_chg_btn.setObjectName("display_chg_btn")
        self.gridLayout_2.addWidget(self.display_chg_btn, 1, 3, 1, 1)
        self.pec_choosed_combobox = QtGui.QComboBox(self.frame)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.pec_choosed_combobox.setFont(font)
        self.pec_choosed_combobox.setObjectName("pec_choosed_combobox")
        self.pec_choosed_combobox.addItem("")
        self.pec_choosed_combobox.addItem("")
        self.pec_choosed_combobox.addItem("")
        self.gridLayout_2.addWidget(self.pec_choosed_combobox, 1, 1, 1, 1)
        self.send_btn = QtGui.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setWeight(9)
        font.setItalic(False)
        font.setBold(False)
        self.send_btn.setFont(font)
        self.send_btn.setWhatsThis("")
        self.send_btn.setObjectName("send_btn")
        self.gridLayout_2.addWidget(self.send_btn, 1, 2, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_2)
        self.reply_lineedit = QtGui.QTextEdit(self.frame)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.reply_lineedit.setFont(font)
        self.reply_lineedit.setReadOnly(True)
        self.reply_lineedit.setObjectName("reply_lineedit")
        self.verticalLayout_5.addWidget(self.reply_lineedit)
        self.groupBox_4 = QtGui.QGroupBox(self.frame)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setWeight(9)
        font.setItalic(False)
        font.setBold(False)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout.setObjectName("gridLayout")
        self.marco_btn_1 = QtGui.QPushButton(self.groupBox_4)
        self.marco_btn_1.setMinimumSize(QtCore.QSize(70, 0))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setWeight(9)
        font.setItalic(False)
        font.setBold(False)
        self.marco_btn_1.setFont(font)
        self.marco_btn_1.setText("")
        self.marco_btn_1.setObjectName("marco_btn_1")
        self.gridLayout.addWidget(self.marco_btn_1, 0, 0, 1, 1)
        self.marco_btn_17 = QtGui.QPushButton(self.groupBox_4)
        self.marco_btn_17.setMinimumSize(QtCore.QSize(70, 0))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setWeight(9)
        font.setItalic(False)
        font.setBold(False)
        self.marco_btn_17.setFont(font)
        self.marco_btn_17.setText("")
        self.marco_btn_17.setObjectName("marco_btn_17")
        self.gridLayout.addWidget(self.marco_btn_17, 2, 0, 1, 1)
        self.marco_btn_21 = QtGui.QPushButton(self.groupBox_4)
        self.marco_btn_21.setMinimumSize(QtCore.QSize(70, 0))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setWeight(9)
        font.setItalic(False)
        font.setBold(False)
        self.marco_btn_21.setFont(font)
        self.marco_btn_21.setText("")
        self.marco_btn_21.setObjectName("marco_btn_21")
        self.gridLayout.addWidget(self.marco_btn_21, 2, 4, 1, 1)
        self.marco_btn_3 = QtGui.QPushButton(self.groupBox_4)
        self.marco_btn_3.setMinimumSize(QtCore.QSize(70, 0))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setWeight(9)
        font.setItalic(False)
        font.setBold(False)
        self.marco_btn_3.setFont(font)
        self.marco_btn_3.setText("")
        self.marco_btn_3.setObjectName("marco_btn_3")
        self.gridLayout.addWidget(self.marco_btn_3, 0, 2, 1, 1)
        self.marco_btn_2 = QtGui.QPushButton(self.groupBox_4)
        self.marco_btn_2.setMinimumSize(QtCore.QSize(70, 0))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setWeight(9)
        font.setItalic(False)
        font.setBold(False)
        self.marco_btn_2.setFont(font)
        self.marco_btn_2.setText("")
        self.marco_btn_2.setObjectName("marco_btn_2")
        self.gridLayout.addWidget(self.marco_btn_2, 0, 1, 1, 1)
        self.marco_btn_13 = QtGui.QPushButton(self.groupBox_4)
        self.marco_btn_13.setMinimumSize(QtCore.QSize(70, 0))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setWeight(9)
        font.setItalic(False)
        font.setBold(False)
        self.marco_btn_13.setFont(font)
        self.marco_btn_13.setText("")
        self.marco_btn_13.setObjectName("marco_btn_13")
        self.gridLayout.addWidget(self.marco_btn_13, 1, 4, 1, 1)
        self.marco_btn_40 = QtGui.QPushButton(self.groupBox_4)
        self.marco_btn_40.setMinimumSize(QtCore.QSize(70, 0))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setWeight(9)
        font.setItalic(False)
        font.setBold(False)
        self.marco_btn_40.setFont(font)
        self.marco_btn_40.setText("")
        self.marco_btn_40.setObjectName("marco_btn_40")
        self.gridLayout.addWidget(self.marco_btn_40, 4, 7, 1, 1)
        self.marco_btn_25 = QtGui.QPushButton(self.groupBox_4)
        self.marco_btn_25.setMinimumSize(QtCore.QSize(70, 0))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setWeight(9)
        font.setItalic(False)
        font.setBold(False)
        self.marco_btn_25.setFont(font)
        self.marco_btn_25.setText("")
        self.marco_btn_25.setObjectName("marco_btn_25")
        self.gridLayout.addWidget(self.marco_btn_25, 3, 0, 1, 1)
        self.marco_btn_9 = QtGui.QPushButton(self.groupBox_4)
        self.marco_btn_9.setMinimumSize(QtCore.QSize(70, 0))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setWeight(9)
        font.setItalic(False)
        font.setBold(False)
        self.marco_btn_9.setFont(font)
        self.marco_btn_9.setText("")
        self.marco_btn_9.setObjectName("marco_btn_9")
        self.gridLayout.addWidget(self.marco_btn_9, 1, 0, 1, 1)
        self.marco_btn_28 = QtGui.QPushButton(self.groupBox_4)
        self.marco_btn_28.setMinimumSize(QtCore.QSize(70, 0))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setWeight(9)
        font.setItalic(False)
        font.setBold(False)
        self.marco_btn_28.setFont(font)
        self.marco_btn_28.setText("")
        self.marco_btn_28.setObjectName("marco_btn_28")
        self.gridLayout.addWidget(self.marco_btn_28, 3, 3, 1, 1)
        self.marco_btn_14 = QtGui.QPushButton(self.groupBox_4)
        self.marco_btn_14.setMinimumSize(QtCore.QSize(70, 0))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setWeight(9)
        font.setItalic(False)
        font.setBold(False)
        self.marco_btn_14.setFont(font)
        self.marco_btn_14.setText("")
        self.marco_btn_14.setObjectName("marco_btn_14")
        self.gridLayout.addWidget(self.marco_btn_14, 1, 5, 1, 1)
        self.marco_btn_18 = QtGui.QPushButton(self.groupBox_4)
        self.marco_btn_18.setMinimumSize(QtCore.QSize(70, 0))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setWeight(9)
        font.setItalic(False)
        font.setBold(False)
        self.marco_btn_18.setFont(font)
        self.marco_btn_18.setText("")
        self.marco_btn_18.setObjectName("marco_btn_18")
        self.gridLayout.addWidget(self.marco_btn_18, 2, 1, 1, 1)
        self.marco_btn_4 = QtGui.QPushButton(self.groupBox_4)
        self.marco_btn_4.setMinimumSize(QtCore.QSize(70, 0))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setWeight(9)
        font.setItalic(False)
        font.setBold(False)
        self.marco_btn_4.setFont(font)
        self.marco_btn_4.setText("")
        self.marco_btn_4.setObjectName("marco_btn_4")
        self.gridLayout.addWidget(self.marco_btn_4, 0, 3, 1, 1)
        self.marco_btn_29 = QtGui.QPushButton(self.groupBox_4)
        self.marco_btn_29.setMinimumSize(QtCore.QSize(70, 0))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setWeight(9)
        font.setItalic(False)
        font.setBold(False)
        self.marco_btn_29.setFont(font)
        self.marco_btn_29.setText("")
        self.marco_btn_29.setObjectName("marco_btn_29")
        self.gridLayout.addWidget(self.marco_btn_29, 3, 4, 1, 1)
        self.marco_btn_22 = QtGui.QPushButton(self.groupBox_4)
        self.marco_btn_22.setMinimumSize(QtCore.QSize(70, 0))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setWeight(9)
        font.setItalic(False)
        font.setBold(False)
        self.marco_btn_22.setFont(font)
        self.marco_btn_22.setText("")
        self.marco_btn_22.setObjectName("marco_btn_22")
        self.gridLayout.addWidget(self.marco_btn_22, 2, 5, 1, 1)
        self.marco_btn_32 = QtGui.QPushButton(self.groupBox_4)
        self.marco_btn_32.setMinimumSize(QtCore.QSize(70, 0))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setWeight(9)
        font.setItalic(False)
        font.setBold(False)
        self.marco_btn_32.setFont(font)
        self.marco_btn_32.setText("")
        self.marco_btn_32.setObjectName("marco_btn_32")
        self.gridLayout.addWidget(self.marco_btn_32, 3, 7, 1, 1)
        self.marco_btn_5 = QtGui.QPushButton(self.groupBox_4)
        self.marco_btn_5.setMinimumSize(QtCore.QSize(70, 0))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setWeight(9)
        font.setItalic(False)
        font.setBold(False)
        self.marco_btn_5.setFont(font)
        self.marco_btn_5.setText("")
        self.marco_btn_5.setObjectName("marco_btn_5")
        self.gridLayout.addWidget(self.marco_btn_5, 0, 4, 1, 1)
        self.marco_btn_38 = QtGui.QPushButton(self.groupBox_4)
        self.marco_btn_38.setMinimumSize(QtCore.QSize(70, 0))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setWeight(9)
        font.setItalic(False)
        font.setBold(False)
        self.marco_btn_38.setFont(font)
        self.marco_btn_38.setText("")
        self.marco_btn_38.setObjectName("marco_btn_38")
        self.gridLayout.addWidget(self.marco_btn_38, 4, 5, 1, 1)
        self.marco_btn_35 = QtGui.QPushButton(self.groupBox_4)
        self.marco_btn_35.setMinimumSize(QtCore.QSize(70, 0))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setWeight(9)
        font.setItalic(False)
        font.setBold(False)
        self.marco_btn_35.setFont(font)
        self.marco_btn_35.setText("")
        self.marco_btn_35.setObjectName("marco_btn_35")
        self.gridLayout.addWidget(self.marco_btn_35, 4, 2, 1, 1)
        self.marco_btn_19 = QtGui.QPushButton(self.groupBox_4)
        self.marco_btn_19.setMinimumSize(QtCore.QSize(70, 0))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setWeight(9)
        font.setItalic(False)
        font.setBold(False)
        self.marco_btn_19.setFont(font)
        self.marco_btn_19.setText("")
        self.marco_btn_19.setObjectName("marco_btn_19")
        self.gridLayout.addWidget(self.marco_btn_19, 2, 2, 1, 1)
        self.marco_btn_10 = QtGui.QPushButton(self.groupBox_4)
        self.marco_btn_10.setMinimumSize(QtCore.QSize(70, 0))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setWeight(9)
        font.setItalic(False)
        font.setBold(False)
        self.marco_btn_10.setFont(font)
        self.marco_btn_10.setText("")
        self.marco_btn_10.setObjectName("marco_btn_10")
        self.gridLayout.addWidget(self.marco_btn_10, 1, 1, 1, 1)
        self.marco_btn_26 = QtGui.QPushButton(self.groupBox_4)
        self.marco_btn_26.setMinimumSize(QtCore.QSize(70, 0))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setWeight(9)
        font.setItalic(False)
        font.setBold(False)
        self.marco_btn_26.setFont(font)
        self.marco_btn_26.setText("")
        self.marco_btn_26.setObjectName("marco_btn_26")
        self.gridLayout.addWidget(self.marco_btn_26, 3, 1, 1, 1)
        self.marco_btn_15 = QtGui.QPushButton(self.groupBox_4)
        self.marco_btn_15.setMinimumSize(QtCore.QSize(70, 0))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setWeight(9)
        font.setItalic(False)
        font.setBold(False)
        self.marco_btn_15.setFont(font)
        self.marco_btn_15.setText("")
        self.marco_btn_15.setObjectName("marco_btn_15")
        self.gridLayout.addWidget(self.marco_btn_15, 1, 6, 1, 1)
        self.marco_btn_33 = QtGui.QPushButton(self.groupBox_4)
        self.marco_btn_33.setMinimumSize(QtCore.QSize(70, 0))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setWeight(9)
        font.setItalic(False)
        font.setBold(False)
        self.marco_btn_33.setFont(font)
        self.marco_btn_33.setText("")
        self.marco_btn_33.setObjectName("marco_btn_33")
        self.gridLayout.addWidget(self.marco_btn_33, 4, 0, 1, 1)
        self.marco_btn_6 = QtGui.QPushButton(self.groupBox_4)
        self.marco_btn_6.setMinimumSize(QtCore.QSize(70, 0))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setWeight(9)
        font.setItalic(False)
        font.setBold(False)
        self.marco_btn_6.setFont(font)
        self.marco_btn_6.setText("")
        self.marco_btn_6.setObjectName("marco_btn_6")
        self.gridLayout.addWidget(self.marco_btn_6, 0, 5, 1, 1)
        self.marco_btn_23 = QtGui.QPushButton(self.groupBox_4)
        self.marco_btn_23.setMinimumSize(QtCore.QSize(70, 0))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setWeight(9)
        font.setItalic(False)
        font.setBold(False)
        self.marco_btn_23.setFont(font)
        self.marco_btn_23.setText("")
        self.marco_btn_23.setObjectName("marco_btn_23")
        self.gridLayout.addWidget(self.marco_btn_23, 2, 6, 1, 1)
        self.marco_btn_30 = QtGui.QPushButton(self.groupBox_4)
        self.marco_btn_30.setMinimumSize(QtCore.QSize(70, 0))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setWeight(9)
        font.setItalic(False)
        font.setBold(False)
        self.marco_btn_30.setFont(font)
        self.marco_btn_30.setText("")
        self.marco_btn_30.setObjectName("marco_btn_30")
        self.gridLayout.addWidget(self.marco_btn_30, 3, 5, 1, 1)
        self.marco_btn_36 = QtGui.QPushButton(self.groupBox_4)
        self.marco_btn_36.setMinimumSize(QtCore.QSize(70, 0))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setWeight(9)
        font.setItalic(False)
        font.setBold(False)
        self.marco_btn_36.setFont(font)
        self.marco_btn_36.setText("")
        self.marco_btn_36.setObjectName("marco_btn_36")
        self.gridLayout.addWidget(self.marco_btn_36, 4, 3, 1, 1)
        self.marco_btn_11 = QtGui.QPushButton(self.groupBox_4)
        self.marco_btn_11.setMinimumSize(QtCore.QSize(70, 0))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setWeight(9)
        font.setItalic(False)
        font.setBold(False)
        self.marco_btn_11.setFont(font)
        self.marco_btn_11.setText("")
        self.marco_btn_11.setObjectName("marco_btn_11")
        self.gridLayout.addWidget(self.marco_btn_11, 1, 2, 1, 1)
        self.marco_btn_7 = QtGui.QPushButton(self.groupBox_4)
        self.marco_btn_7.setMinimumSize(QtCore.QSize(70, 0))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setWeight(9)
        font.setItalic(False)
        font.setBold(False)
        self.marco_btn_7.setFont(font)
        self.marco_btn_7.setText("")
        self.marco_btn_7.setObjectName("marco_btn_7")
        self.gridLayout.addWidget(self.marco_btn_7, 0, 6, 1, 1)
        self.marco_btn_39 = QtGui.QPushButton(self.groupBox_4)
        self.marco_btn_39.setMinimumSize(QtCore.QSize(70, 0))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setWeight(9)
        font.setItalic(False)
        font.setBold(False)
        self.marco_btn_39.setFont(font)
        self.marco_btn_39.setText("")
        self.marco_btn_39.setObjectName("marco_btn_39")
        self.gridLayout.addWidget(self.marco_btn_39, 4, 6, 1, 1)
        self.marco_btn_27 = QtGui.QPushButton(self.groupBox_4)
        self.marco_btn_27.setMinimumSize(QtCore.QSize(70, 0))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setWeight(9)
        font.setItalic(False)
        font.setBold(False)
        self.marco_btn_27.setFont(font)
        self.marco_btn_27.setText("")
        self.marco_btn_27.setObjectName("marco_btn_27")
        self.gridLayout.addWidget(self.marco_btn_27, 3, 2, 1, 1)
        self.marco_btn_24 = QtGui.QPushButton(self.groupBox_4)
        self.marco_btn_24.setMinimumSize(QtCore.QSize(70, 0))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setWeight(9)
        font.setItalic(False)
        font.setBold(False)
        self.marco_btn_24.setFont(font)
        self.marco_btn_24.setText("")
        self.marco_btn_24.setObjectName("marco_btn_24")
        self.gridLayout.addWidget(self.marco_btn_24, 2, 7, 1, 1)
        self.marco_btn_20 = QtGui.QPushButton(self.groupBox_4)
        self.marco_btn_20.setMinimumSize(QtCore.QSize(70, 0))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setWeight(9)
        font.setItalic(False)
        font.setBold(False)
        self.marco_btn_20.setFont(font)
        self.marco_btn_20.setText("")
        self.marco_btn_20.setObjectName("marco_btn_20")
        self.gridLayout.addWidget(self.marco_btn_20, 2, 3, 1, 1)
        self.marco_btn_16 = QtGui.QPushButton(self.groupBox_4)
        self.marco_btn_16.setMinimumSize(QtCore.QSize(70, 0))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setWeight(9)
        font.setItalic(False)
        font.setBold(False)
        self.marco_btn_16.setFont(font)
        self.marco_btn_16.setText("")
        self.marco_btn_16.setObjectName("marco_btn_16")
        self.gridLayout.addWidget(self.marco_btn_16, 1, 7, 1, 1)
        self.marco_btn_8 = QtGui.QPushButton(self.groupBox_4)
        self.marco_btn_8.setMinimumSize(QtCore.QSize(70, 0))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setWeight(9)
        font.setItalic(False)
        font.setBold(False)
        self.marco_btn_8.setFont(font)
        self.marco_btn_8.setText("")
        self.marco_btn_8.setObjectName("marco_btn_8")
        self.gridLayout.addWidget(self.marco_btn_8, 0, 7, 1, 1)
        self.marco_btn_34 = QtGui.QPushButton(self.groupBox_4)
        self.marco_btn_34.setMinimumSize(QtCore.QSize(70, 0))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setWeight(9)
        font.setItalic(False)
        font.setBold(False)
        self.marco_btn_34.setFont(font)
        self.marco_btn_34.setText("")
        self.marco_btn_34.setObjectName("marco_btn_34")
        self.gridLayout.addWidget(self.marco_btn_34, 4, 1, 1, 1)
        self.marco_btn_12 = QtGui.QPushButton(self.groupBox_4)
        self.marco_btn_12.setMinimumSize(QtCore.QSize(70, 0))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setWeight(9)
        font.setItalic(False)
        font.setBold(False)
        self.marco_btn_12.setFont(font)
        self.marco_btn_12.setText("")
        self.marco_btn_12.setObjectName("marco_btn_12")
        self.gridLayout.addWidget(self.marco_btn_12, 1, 3, 1, 1)
        self.marco_btn_37 = QtGui.QPushButton(self.groupBox_4)
        self.marco_btn_37.setMinimumSize(QtCore.QSize(70, 0))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setWeight(9)
        font.setItalic(False)
        font.setBold(False)
        self.marco_btn_37.setFont(font)
        self.marco_btn_37.setText("")
        self.marco_btn_37.setObjectName("marco_btn_37")
        self.gridLayout.addWidget(self.marco_btn_37, 4, 4, 1, 1)
        self.marco_btn_31 = QtGui.QPushButton(self.groupBox_4)
        self.marco_btn_31.setMinimumSize(QtCore.QSize(70, 0))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setWeight(9)
        font.setItalic(False)
        font.setBold(False)
        self.marco_btn_31.setFont(font)
        self.marco_btn_31.setText("")
        self.marco_btn_31.setObjectName("marco_btn_31")
        self.gridLayout.addWidget(self.marco_btn_31, 3, 6, 1, 1)
        self.verticalLayout_5.addWidget(self.groupBox_4)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setWeight(9)
        font.setItalic(False)
        font.setBold(False)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.marco_string_lineedit = QtGui.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(14)
        self.marco_string_lineedit.setFont(font)
        self.marco_string_lineedit.setReadOnly(True)
        self.marco_string_lineedit.setObjectName("marco_string_lineedit")
        self.horizontalLayout_2.addWidget(self.marco_string_lineedit)
        self.horizontalLayout_2.setStretch(0, 2)
        self.horizontalLayout_2.setStretch(1, 13)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1302, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "ComportTesting_Ver. 4.0 by JiRong", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Setting", None, QtGui.QApplication.UnicodeUTF8))
        self.connect_btn.setText(QtGui.QApplication.translate("MainWindow", "Connect", None, QtGui.QApplication.UnicodeUTF8))
        self.rescan_btn.setText(QtGui.QApplication.translate("MainWindow", "ReScan", None, QtGui.QApplication.UnicodeUTF8))
        self.show_about_btn.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.exit_btn.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "Com", None, QtGui.QApplication.UnicodeUTF8))
        self.rate9600_rbtn.setText(QtGui.QApplication.translate("MainWindow", "9600", None, QtGui.QApplication.UnicodeUTF8))
        self.rate19200_rbtn.setText(QtGui.QApplication.translate("MainWindow", "19200", None, QtGui.QApplication.UnicodeUTF8))
        self.rate115200_rbtn.setText(QtGui.QApplication.translate("MainWindow", "115200", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("MainWindow", "Other", None, QtGui.QApplication.UnicodeUTF8))
        self.set_marco_btn.setText(QtGui.QApplication.translate("MainWindow", "SET", None, QtGui.QApplication.UnicodeUTF8))
        self.open_marco_file_btn.setText(QtGui.QApplication.translate("MainWindow", "OPEN", None, QtGui.QApplication.UnicodeUTF8))
        self.save_marco_file_btn.setText(QtGui.QApplication.translate("MainWindow", "SAVE", None, QtGui.QApplication.UnicodeUTF8))
        self.show_ascii_btn.setText(QtGui.QApplication.translate("MainWindow", "ASCII Table", None, QtGui.QApplication.UnicodeUTF8))
        self.display_chg_btn.setText(QtGui.QApplication.translate("MainWindow", "ASCII", None, QtGui.QApplication.UnicodeUTF8))
        self.pec_choosed_combobox.setItemText(0, QtGui.QApplication.translate("MainWindow", "NONE", None, QtGui.QApplication.UnicodeUTF8))
        self.pec_choosed_combobox.setItemText(1, QtGui.QApplication.translate("MainWindow", "1Byte PEC 2\'s complement", None, QtGui.QApplication.UnicodeUTF8))
        self.pec_choosed_combobox.setItemText(2, QtGui.QApplication.translate("MainWindow", "2Byte PEC 2\'s complement", None, QtGui.QApplication.UnicodeUTF8))
        self.send_btn.setText(QtGui.QApplication.translate("MainWindow", "Send", None, QtGui.QApplication.UnicodeUTF8))
        self.reply_lineedit.setHtml(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'PMingLiU\'; font-size:16pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("MainWindow", "Marco", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Marco Command", None, QtGui.QApplication.UnicodeUTF8))

