# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Setting.ui'
#
# Created: Wed Jan 16 09:50:30 2019
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_ScriptSetting(object):
    def setupUi(self, ScriptSetting):
        ScriptSetting.setObjectName("ScriptSetting")
        ScriptSetting.resize(1033, 715)
        ScriptSetting.setMinimumSize(QtCore.QSize(1033, 715))
        ScriptSetting.setMaximumSize(QtCore.QSize(1033, 728))
        ScriptSetting.setStyleSheet("QFrame{\n"
"    background-color: #EEEEEE;\n"
"}\n"
"QPushButton{\n"
"    background-color:     #CCCCCC;\n"
"    color: rgb(0, 0, 0);\n"
"    font: 75 14pt \"Times New Roman\";\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: #0078D4;\n"
"    color: rgb(255, 255, 255);\n"
"    font: 14pt \"Calibri\";\n"
"}\n"
"QLabel{\n"
"    color: rgb(0, 0, 0);\n"
"background-color: #EEEEEE;\n"
"    font: 75 14pt \"Calibri\";\n"
"}\n"
"\n"
"QTextEdit{\n"
"background-color: #828EAE;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QLineEdit{\n"
"    background-color: #FFFFFF;\n"
"    color: rgb(0, 0, 0);\n"
"    border-width: 2px;\n"
"    border-color: rgb(0, 0, 0);\n"
"}\n"
"QLineEdit:hover{\n"
"    border: 1px solid blue; \n"
"    background-color: #FFFFFF;\n"
"}")
        self.gridLayout = QtGui.QGridLayout(ScriptSetting)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(7)
        self.gridLayout.setVerticalSpacing(2)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtGui.QFrame(ScriptSetting)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtGui.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_1 = QtGui.QPushButton(self.frame)
        self.pushButton_1.setMinimumSize(QtCore.QSize(93, 28))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setWeight(9)
        font.setItalic(False)
        font.setBold(False)
        self.pushButton_1.setFont(font)
        self.pushButton_1.setText("")
        self.pushButton_1.setObjectName("pushButton_1")
        self.gridLayout_2.addWidget(self.pushButton_1, 0, 2, 1, 1)
        self.pushButton_20 = QtGui.QPushButton(self.frame)
        self.pushButton_20.setMinimumSize(QtCore.QSize(93, 28))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setWeight(9)
        font.setItalic(False)
        font.setBold(False)
        self.pushButton_20.setFont(font)
        self.pushButton_20.setText("")
        self.pushButton_20.setObjectName("pushButton_20")
        self.gridLayout_2.addWidget(self.pushButton_20, 19, 2, 1, 1)
        self.pushButton_4 = QtGui.QPushButton(self.frame)
        self.pushButton_4.setMinimumSize(QtCore.QSize(93, 28))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setWeight(9)
        font.setItalic(False)
        font.setBold(False)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setText("")
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_2.addWidget(self.pushButton_4, 3, 2, 1, 1)
        self.pushButton_19 = QtGui.QPushButton(self.frame)
        self.pushButton_19.setMinimumSize(QtCore.QSize(93, 28))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setWeight(9)
        font.setItalic(False)
        font.setBold(False)
        self.pushButton_19.setFont(font)
        self.pushButton_19.setText("")
        self.pushButton_19.setObjectName("pushButton_19")
        self.gridLayout_2.addWidget(self.pushButton_19, 18, 2, 1, 1)
        self.pushButton_3 = QtGui.QPushButton(self.frame)
        self.pushButton_3.setMinimumSize(QtCore.QSize(93, 28))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setWeight(9)
        font.setItalic(False)
        font.setBold(False)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setText("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_2.addWidget(self.pushButton_3, 2, 2, 1, 1)
        self.str_lineedit_1 = QtGui.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(12)
        self.str_lineedit_1.setFont(font)
        self.str_lineedit_1.setObjectName("str_lineedit_1")
        self.gridLayout_2.addWidget(self.str_lineedit_1, 0, 0, 1, 1)
        self.pushButton_2 = QtGui.QPushButton(self.frame)
        self.pushButton_2.setMinimumSize(QtCore.QSize(93, 28))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setWeight(9)
        font.setItalic(False)
        font.setBold(False)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_2.addWidget(self.pushButton_2, 1, 2, 1, 1)
        self.pushButton_5 = QtGui.QPushButton(self.frame)
        self.pushButton_5.setMinimumSize(QtCore.QSize(93, 28))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setWeight(9)
        font.setItalic(False)
        font.setBold(False)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setText("")
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_2.addWidget(self.pushButton_5, 4, 2, 1, 1)
        self.pushButton_15 = QtGui.QPushButton(self.frame)
        self.pushButton_15.setMinimumSize(QtCore.QSize(93, 28))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setWeight(9)
        font.setItalic(False)
        font.setBold(False)
        self.pushButton_15.setFont(font)
        self.pushButton_15.setText("")
        self.pushButton_15.setObjectName("pushButton_15")
        self.gridLayout_2.addWidget(self.pushButton_15, 14, 2, 1, 1)
        self.pushButton_17 = QtGui.QPushButton(self.frame)
        self.pushButton_17.setMinimumSize(QtCore.QSize(93, 28))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setWeight(9)
        font.setItalic(False)
        font.setBold(False)
        self.pushButton_17.setFont(font)
        self.pushButton_17.setText("")
        self.pushButton_17.setObjectName("pushButton_17")
        self.gridLayout_2.addWidget(self.pushButton_17, 16, 2, 1, 1)
        self.pushButton_16 = QtGui.QPushButton(self.frame)
        self.pushButton_16.setMinimumSize(QtCore.QSize(93, 28))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setWeight(9)
        font.setItalic(False)
        font.setBold(False)
        self.pushButton_16.setFont(font)
        self.pushButton_16.setText("")
        self.pushButton_16.setObjectName("pushButton_16")
        self.gridLayout_2.addWidget(self.pushButton_16, 15, 2, 1, 1)
        self.pushButton_14 = QtGui.QPushButton(self.frame)
        self.pushButton_14.setMinimumSize(QtCore.QSize(93, 28))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setWeight(9)
        font.setItalic(False)
        font.setBold(False)
        self.pushButton_14.setFont(font)
        self.pushButton_14.setText("")
        self.pushButton_14.setObjectName("pushButton_14")
        self.gridLayout_2.addWidget(self.pushButton_14, 13, 2, 1, 1)
        self.pushButton_18 = QtGui.QPushButton(self.frame)
        self.pushButton_18.setMinimumSize(QtCore.QSize(93, 28))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setWeight(9)
        font.setItalic(False)
        font.setBold(False)
        self.pushButton_18.setFont(font)
        self.pushButton_18.setText("")
        self.pushButton_18.setObjectName("pushButton_18")
        self.gridLayout_2.addWidget(self.pushButton_18, 17, 2, 1, 1)
        self.pushButton_21 = QtGui.QPushButton(self.frame)
        self.pushButton_21.setMinimumSize(QtCore.QSize(93, 28))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setWeight(9)
        font.setItalic(False)
        font.setBold(False)
        self.pushButton_21.setFont(font)
        self.pushButton_21.setText("")
        self.pushButton_21.setObjectName("pushButton_21")
        self.gridLayout_2.addWidget(self.pushButton_21, 0, 5, 1, 1)
        self.pushButton_6 = QtGui.QPushButton(self.frame)
        self.pushButton_6.setMinimumSize(QtCore.QSize(93, 28))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setWeight(9)
        font.setItalic(False)
        font.setBold(False)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setText("")
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_2.addWidget(self.pushButton_6, 5, 2, 1, 1)
        self.pushButton_9 = QtGui.QPushButton(self.frame)
        self.pushButton_9.setMinimumSize(QtCore.QSize(93, 28))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setWeight(9)
        font.setItalic(False)
        font.setBold(False)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setText("")
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout_2.addWidget(self.pushButton_9, 8, 2, 1, 1)
        self.pushButton_8 = QtGui.QPushButton(self.frame)
        self.pushButton_8.setMinimumSize(QtCore.QSize(93, 28))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setWeight(9)
        font.setItalic(False)
        font.setBold(False)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setText("")
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout_2.addWidget(self.pushButton_8, 7, 2, 1, 1)
        self.pushButton_7 = QtGui.QPushButton(self.frame)
        self.pushButton_7.setMinimumSize(QtCore.QSize(93, 28))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setWeight(9)
        font.setItalic(False)
        font.setBold(False)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setText("")
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout_2.addWidget(self.pushButton_7, 6, 2, 1, 1)
        self.pushButton_10 = QtGui.QPushButton(self.frame)
        self.pushButton_10.setMinimumSize(QtCore.QSize(93, 28))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setWeight(9)
        font.setItalic(False)
        font.setBold(False)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setText("")
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout_2.addWidget(self.pushButton_10, 9, 2, 1, 1)
        self.pushButton_11 = QtGui.QPushButton(self.frame)
        self.pushButton_11.setMinimumSize(QtCore.QSize(93, 28))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setWeight(9)
        font.setItalic(False)
        font.setBold(False)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setText("")
        self.pushButton_11.setObjectName("pushButton_11")
        self.gridLayout_2.addWidget(self.pushButton_11, 10, 2, 1, 1)
        self.pushButton_12 = QtGui.QPushButton(self.frame)
        self.pushButton_12.setMinimumSize(QtCore.QSize(93, 28))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setWeight(9)
        font.setItalic(False)
        font.setBold(False)
        self.pushButton_12.setFont(font)
        self.pushButton_12.setText("")
        self.pushButton_12.setObjectName("pushButton_12")
        self.gridLayout_2.addWidget(self.pushButton_12, 11, 2, 1, 1)
        self.pushButton_13 = QtGui.QPushButton(self.frame)
        self.pushButton_13.setMinimumSize(QtCore.QSize(93, 28))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setWeight(9)
        font.setItalic(False)
        font.setBold(False)
        self.pushButton_13.setFont(font)
        self.pushButton_13.setText("")
        self.pushButton_13.setObjectName("pushButton_13")
        self.gridLayout_2.addWidget(self.pushButton_13, 12, 2, 1, 1)
        self.ok_btn = QtGui.QPushButton(self.frame)
        self.ok_btn.setMinimumSize(QtCore.QSize(93, 28))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setWeight(9)
        font.setItalic(False)
        font.setBold(False)
        self.ok_btn.setFont(font)
        self.ok_btn.setObjectName("ok_btn")
        self.gridLayout_2.addWidget(self.ok_btn, 20, 5, 1, 1)
        self.pushButton_22 = QtGui.QPushButton(self.frame)
        self.pushButton_22.setMinimumSize(QtCore.QSize(93, 28))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setWeight(9)
        font.setItalic(False)
        font.setBold(False)
        self.pushButton_22.setFont(font)
        self.pushButton_22.setText("")
        self.pushButton_22.setObjectName("pushButton_22")
        self.gridLayout_2.addWidget(self.pushButton_22, 1, 5, 1, 1)
        self.pushButton_26 = QtGui.QPushButton(self.frame)
        self.pushButton_26.setMinimumSize(QtCore.QSize(93, 28))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setWeight(9)
        font.setItalic(False)
        font.setBold(False)
        self.pushButton_26.setFont(font)
        self.pushButton_26.setText("")
        self.pushButton_26.setObjectName("pushButton_26")
        self.gridLayout_2.addWidget(self.pushButton_26, 5, 5, 1, 1)
        self.pushButton_23 = QtGui.QPushButton(self.frame)
        self.pushButton_23.setMinimumSize(QtCore.QSize(93, 28))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setWeight(9)
        font.setItalic(False)
        font.setBold(False)
        self.pushButton_23.setFont(font)
        self.pushButton_23.setText("")
        self.pushButton_23.setObjectName("pushButton_23")
        self.gridLayout_2.addWidget(self.pushButton_23, 2, 5, 1, 1)
        self.pushButton_25 = QtGui.QPushButton(self.frame)
        self.pushButton_25.setMinimumSize(QtCore.QSize(93, 28))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setWeight(9)
        font.setItalic(False)
        font.setBold(False)
        self.pushButton_25.setFont(font)
        self.pushButton_25.setText("")
        self.pushButton_25.setObjectName("pushButton_25")
        self.gridLayout_2.addWidget(self.pushButton_25, 4, 5, 1, 1)
        self.pushButton_24 = QtGui.QPushButton(self.frame)
        self.pushButton_24.setMinimumSize(QtCore.QSize(93, 28))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setWeight(9)
        font.setItalic(False)
        font.setBold(False)
        self.pushButton_24.setFont(font)
        self.pushButton_24.setText("")
        self.pushButton_24.setObjectName("pushButton_24")
        self.gridLayout_2.addWidget(self.pushButton_24, 3, 5, 1, 1)
        self.pushButton_27 = QtGui.QPushButton(self.frame)
        self.pushButton_27.setMinimumSize(QtCore.QSize(93, 28))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setWeight(9)
        font.setItalic(False)
        font.setBold(False)
        self.pushButton_27.setFont(font)
        self.pushButton_27.setText("")
        self.pushButton_27.setObjectName("pushButton_27")
        self.gridLayout_2.addWidget(self.pushButton_27, 6, 5, 1, 1)
        self.pushButton_28 = QtGui.QPushButton(self.frame)
        self.pushButton_28.setMinimumSize(QtCore.QSize(93, 28))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setWeight(9)
        font.setItalic(False)
        font.setBold(False)
        self.pushButton_28.setFont(font)
        self.pushButton_28.setText("")
        self.pushButton_28.setObjectName("pushButton_28")
        self.gridLayout_2.addWidget(self.pushButton_28, 7, 5, 1, 1)
        self.pushButton_30 = QtGui.QPushButton(self.frame)
        self.pushButton_30.setMinimumSize(QtCore.QSize(93, 28))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setWeight(9)
        font.setItalic(False)
        font.setBold(False)
        self.pushButton_30.setFont(font)
        self.pushButton_30.setText("")
        self.pushButton_30.setObjectName("pushButton_30")
        self.gridLayout_2.addWidget(self.pushButton_30, 9, 5, 1, 1)
        self.pushButton_33 = QtGui.QPushButton(self.frame)
        self.pushButton_33.setMinimumSize(QtCore.QSize(93, 28))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setWeight(9)
        font.setItalic(False)
        font.setBold(False)
        self.pushButton_33.setFont(font)
        self.pushButton_33.setText("")
        self.pushButton_33.setObjectName("pushButton_33")
        self.gridLayout_2.addWidget(self.pushButton_33, 12, 5, 1, 1)
        self.pushButton_40 = QtGui.QPushButton(self.frame)
        self.pushButton_40.setMinimumSize(QtCore.QSize(93, 28))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setWeight(9)
        font.setItalic(False)
        font.setBold(False)
        self.pushButton_40.setFont(font)
        self.pushButton_40.setText("")
        self.pushButton_40.setObjectName("pushButton_40")
        self.gridLayout_2.addWidget(self.pushButton_40, 19, 5, 1, 1)
        self.pushButton_38 = QtGui.QPushButton(self.frame)
        self.pushButton_38.setMinimumSize(QtCore.QSize(93, 28))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setWeight(9)
        font.setItalic(False)
        font.setBold(False)
        self.pushButton_38.setFont(font)
        self.pushButton_38.setText("")
        self.pushButton_38.setObjectName("pushButton_38")
        self.gridLayout_2.addWidget(self.pushButton_38, 17, 5, 1, 1)
        self.pushButton_36 = QtGui.QPushButton(self.frame)
        self.pushButton_36.setMinimumSize(QtCore.QSize(93, 28))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setWeight(9)
        font.setItalic(False)
        font.setBold(False)
        self.pushButton_36.setFont(font)
        self.pushButton_36.setText("")
        self.pushButton_36.setObjectName("pushButton_36")
        self.gridLayout_2.addWidget(self.pushButton_36, 15, 5, 1, 1)
        self.pushButton_31 = QtGui.QPushButton(self.frame)
        self.pushButton_31.setMinimumSize(QtCore.QSize(93, 28))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setWeight(9)
        font.setItalic(False)
        font.setBold(False)
        self.pushButton_31.setFont(font)
        self.pushButton_31.setText("")
        self.pushButton_31.setObjectName("pushButton_31")
        self.gridLayout_2.addWidget(self.pushButton_31, 10, 5, 1, 1)
        self.pushButton_34 = QtGui.QPushButton(self.frame)
        self.pushButton_34.setMinimumSize(QtCore.QSize(93, 28))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setWeight(9)
        font.setItalic(False)
        font.setBold(False)
        self.pushButton_34.setFont(font)
        self.pushButton_34.setText("")
        self.pushButton_34.setObjectName("pushButton_34")
        self.gridLayout_2.addWidget(self.pushButton_34, 13, 5, 1, 1)
        self.pushButton_29 = QtGui.QPushButton(self.frame)
        self.pushButton_29.setMinimumSize(QtCore.QSize(93, 28))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setWeight(9)
        font.setItalic(False)
        font.setBold(False)
        self.pushButton_29.setFont(font)
        self.pushButton_29.setText("")
        self.pushButton_29.setObjectName("pushButton_29")
        self.gridLayout_2.addWidget(self.pushButton_29, 8, 5, 1, 1)
        self.pushButton_39 = QtGui.QPushButton(self.frame)
        self.pushButton_39.setMinimumSize(QtCore.QSize(93, 28))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setWeight(9)
        font.setItalic(False)
        font.setBold(False)
        self.pushButton_39.setFont(font)
        self.pushButton_39.setText("")
        self.pushButton_39.setObjectName("pushButton_39")
        self.gridLayout_2.addWidget(self.pushButton_39, 18, 5, 1, 1)
        self.pushButton_32 = QtGui.QPushButton(self.frame)
        self.pushButton_32.setMinimumSize(QtCore.QSize(93, 28))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setWeight(9)
        font.setItalic(False)
        font.setBold(False)
        self.pushButton_32.setFont(font)
        self.pushButton_32.setText("")
        self.pushButton_32.setObjectName("pushButton_32")
        self.gridLayout_2.addWidget(self.pushButton_32, 11, 5, 1, 1)
        self.pushButton_37 = QtGui.QPushButton(self.frame)
        self.pushButton_37.setMinimumSize(QtCore.QSize(93, 28))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setWeight(9)
        font.setItalic(False)
        font.setBold(False)
        self.pushButton_37.setFont(font)
        self.pushButton_37.setText("")
        self.pushButton_37.setObjectName("pushButton_37")
        self.gridLayout_2.addWidget(self.pushButton_37, 16, 5, 1, 1)
        self.pushButton_35 = QtGui.QPushButton(self.frame)
        self.pushButton_35.setMinimumSize(QtCore.QSize(93, 28))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setWeight(9)
        font.setItalic(False)
        font.setBold(False)
        self.pushButton_35.setFont(font)
        self.pushButton_35.setText("")
        self.pushButton_35.setObjectName("pushButton_35")
        self.gridLayout_2.addWidget(self.pushButton_35, 14, 5, 1, 1)
        self.str_lineedit_25 = QtGui.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(12)
        self.str_lineedit_25.setFont(font)
        self.str_lineedit_25.setObjectName("str_lineedit_25")
        self.gridLayout_2.addWidget(self.str_lineedit_25, 4, 3, 1, 1)
        self.cmd_name_lineedit_9 = QtGui.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(12)
        self.cmd_name_lineedit_9.setFont(font)
        self.cmd_name_lineedit_9.setObjectName("cmd_name_lineedit_9")
        self.gridLayout_2.addWidget(self.cmd_name_lineedit_9, 8, 1, 1, 1)
        self.cmd_name_lineedit_16 = QtGui.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(12)
        self.cmd_name_lineedit_16.setFont(font)
        self.cmd_name_lineedit_16.setObjectName("cmd_name_lineedit_16")
        self.gridLayout_2.addWidget(self.cmd_name_lineedit_16, 15, 1, 1, 1)
        self.str_lineedit_16 = QtGui.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(12)
        self.str_lineedit_16.setFont(font)
        self.str_lineedit_16.setObjectName("str_lineedit_16")
        self.gridLayout_2.addWidget(self.str_lineedit_16, 15, 0, 1, 1)
        self.str_lineedit_34 = QtGui.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(12)
        self.str_lineedit_34.setFont(font)
        self.str_lineedit_34.setObjectName("str_lineedit_34")
        self.gridLayout_2.addWidget(self.str_lineedit_34, 13, 3, 1, 1)
        self.cmd_name_lineedit_33 = QtGui.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(12)
        self.cmd_name_lineedit_33.setFont(font)
        self.cmd_name_lineedit_33.setObjectName("cmd_name_lineedit_33")
        self.gridLayout_2.addWidget(self.cmd_name_lineedit_33, 12, 4, 1, 1)
        self.str_lineedit_7 = QtGui.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(12)
        self.str_lineedit_7.setFont(font)
        self.str_lineedit_7.setObjectName("str_lineedit_7")
        self.gridLayout_2.addWidget(self.str_lineedit_7, 6, 0, 1, 1)
        self.cmd_name_lineedit_2 = QtGui.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(12)
        self.cmd_name_lineedit_2.setFont(font)
        self.cmd_name_lineedit_2.setObjectName("cmd_name_lineedit_2")
        self.gridLayout_2.addWidget(self.cmd_name_lineedit_2, 1, 1, 1, 1)
        self.cmd_name_lineedit_23 = QtGui.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(12)
        self.cmd_name_lineedit_23.setFont(font)
        self.cmd_name_lineedit_23.setObjectName("cmd_name_lineedit_23")
        self.gridLayout_2.addWidget(self.cmd_name_lineedit_23, 2, 4, 1, 1)
        self.str_lineedit_26 = QtGui.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(12)
        self.str_lineedit_26.setFont(font)
        self.str_lineedit_26.setObjectName("str_lineedit_26")
        self.gridLayout_2.addWidget(self.str_lineedit_26, 5, 3, 1, 1)
        self.cmd_name_lineedit_29 = QtGui.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(12)
        self.cmd_name_lineedit_29.setFont(font)
        self.cmd_name_lineedit_29.setObjectName("cmd_name_lineedit_29")
        self.gridLayout_2.addWidget(self.cmd_name_lineedit_29, 8, 4, 1, 1)
        self.str_lineedit_17 = QtGui.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(12)
        self.str_lineedit_17.setFont(font)
        self.str_lineedit_17.setObjectName("str_lineedit_17")
        self.gridLayout_2.addWidget(self.str_lineedit_17, 16, 0, 1, 1)
        self.cmd_name_lineedit_10 = QtGui.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(12)
        self.cmd_name_lineedit_10.setFont(font)
        self.cmd_name_lineedit_10.setObjectName("cmd_name_lineedit_10")
        self.gridLayout_2.addWidget(self.cmd_name_lineedit_10, 9, 1, 1, 1)
        self.str_lineedit_8 = QtGui.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(12)
        self.str_lineedit_8.setFont(font)
        self.str_lineedit_8.setObjectName("str_lineedit_8")
        self.gridLayout_2.addWidget(self.str_lineedit_8, 7, 0, 1, 1)
        self.cmd_name_lineedit_17 = QtGui.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(12)
        self.cmd_name_lineedit_17.setFont(font)
        self.cmd_name_lineedit_17.setObjectName("cmd_name_lineedit_17")
        self.gridLayout_2.addWidget(self.cmd_name_lineedit_17, 16, 1, 1, 1)
        self.str_lineedit_35 = QtGui.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(12)
        self.str_lineedit_35.setFont(font)
        self.str_lineedit_35.setObjectName("str_lineedit_35")
        self.gridLayout_2.addWidget(self.str_lineedit_35, 14, 3, 1, 1)
        self.cmd_name_lineedit_3 = QtGui.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(12)
        self.cmd_name_lineedit_3.setFont(font)
        self.cmd_name_lineedit_3.setObjectName("cmd_name_lineedit_3")
        self.gridLayout_2.addWidget(self.cmd_name_lineedit_3, 2, 1, 1, 1)
        self.cmd_name_lineedit_39 = QtGui.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(12)
        self.cmd_name_lineedit_39.setFont(font)
        self.cmd_name_lineedit_39.setObjectName("cmd_name_lineedit_39")
        self.gridLayout_2.addWidget(self.cmd_name_lineedit_39, 18, 4, 1, 1)
        self.str_lineedit_27 = QtGui.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(12)
        self.str_lineedit_27.setFont(font)
        self.str_lineedit_27.setObjectName("str_lineedit_27")
        self.gridLayout_2.addWidget(self.str_lineedit_27, 6, 3, 1, 1)
        self.str_lineedit_9 = QtGui.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(12)
        self.str_lineedit_9.setFont(font)
        self.str_lineedit_9.setObjectName("str_lineedit_9")
        self.gridLayout_2.addWidget(self.str_lineedit_9, 8, 0, 1, 1)
        self.cmd_name_lineedit_34 = QtGui.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(12)
        self.cmd_name_lineedit_34.setFont(font)
        self.cmd_name_lineedit_34.setObjectName("cmd_name_lineedit_34")
        self.gridLayout_2.addWidget(self.cmd_name_lineedit_34, 13, 4, 1, 1)
        self.str_lineedit_18 = QtGui.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(12)
        self.str_lineedit_18.setFont(font)
        self.str_lineedit_18.setObjectName("str_lineedit_18")
        self.gridLayout_2.addWidget(self.str_lineedit_18, 17, 0, 1, 1)
        self.cmd_name_lineedit_24 = QtGui.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(12)
        self.cmd_name_lineedit_24.setFont(font)
        self.cmd_name_lineedit_24.setObjectName("cmd_name_lineedit_24")
        self.gridLayout_2.addWidget(self.cmd_name_lineedit_24, 3, 4, 1, 1)
        self.str_lineedit_36 = QtGui.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(12)
        self.str_lineedit_36.setFont(font)
        self.str_lineedit_36.setObjectName("str_lineedit_36")
        self.gridLayout_2.addWidget(self.str_lineedit_36, 15, 3, 1, 1)
        self.cmd_name_lineedit_18 = QtGui.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(12)
        self.cmd_name_lineedit_18.setFont(font)
        self.cmd_name_lineedit_18.setObjectName("cmd_name_lineedit_18")
        self.gridLayout_2.addWidget(self.cmd_name_lineedit_18, 17, 1, 1, 1)
        self.cmd_name_lineedit_11 = QtGui.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(12)
        self.cmd_name_lineedit_11.setFont(font)
        self.cmd_name_lineedit_11.setObjectName("cmd_name_lineedit_11")
        self.gridLayout_2.addWidget(self.cmd_name_lineedit_11, 10, 1, 1, 1)
        self.str_lineedit_10 = QtGui.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(12)
        self.str_lineedit_10.setFont(font)
        self.str_lineedit_10.setObjectName("str_lineedit_10")
        self.gridLayout_2.addWidget(self.str_lineedit_10, 9, 0, 1, 1)
        self.cmd_name_lineedit_4 = QtGui.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(12)
        self.cmd_name_lineedit_4.setFont(font)
        self.cmd_name_lineedit_4.setObjectName("cmd_name_lineedit_4")
        self.gridLayout_2.addWidget(self.cmd_name_lineedit_4, 3, 1, 1, 1)
        self.str_lineedit_28 = QtGui.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(12)
        self.str_lineedit_28.setFont(font)
        self.str_lineedit_28.setObjectName("str_lineedit_28")
        self.gridLayout_2.addWidget(self.str_lineedit_28, 7, 3, 1, 1)
        self.cmd_name_lineedit_30 = QtGui.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(12)
        self.cmd_name_lineedit_30.setFont(font)
        self.cmd_name_lineedit_30.setObjectName("cmd_name_lineedit_30")
        self.gridLayout_2.addWidget(self.cmd_name_lineedit_30, 9, 4, 1, 1)
        self.str_lineedit_19 = QtGui.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(12)
        self.str_lineedit_19.setFont(font)
        self.str_lineedit_19.setObjectName("str_lineedit_19")
        self.gridLayout_2.addWidget(self.str_lineedit_19, 18, 0, 1, 1)
        self.str_lineedit_11 = QtGui.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(12)
        self.str_lineedit_11.setFont(font)
        self.str_lineedit_11.setObjectName("str_lineedit_11")
        self.gridLayout_2.addWidget(self.str_lineedit_11, 10, 0, 1, 1)
        self.cmd_name_lineedit_25 = QtGui.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(12)
        self.cmd_name_lineedit_25.setFont(font)
        self.cmd_name_lineedit_25.setObjectName("cmd_name_lineedit_25")
        self.gridLayout_2.addWidget(self.cmd_name_lineedit_25, 4, 4, 1, 1)
        self.cmd_name_lineedit_35 = QtGui.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(12)
        self.cmd_name_lineedit_35.setFont(font)
        self.cmd_name_lineedit_35.setObjectName("cmd_name_lineedit_35")
        self.gridLayout_2.addWidget(self.cmd_name_lineedit_35, 14, 4, 1, 1)
        self.str_lineedit_20 = QtGui.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(12)
        self.str_lineedit_20.setFont(font)
        self.str_lineedit_20.setObjectName("str_lineedit_20")
        self.gridLayout_2.addWidget(self.str_lineedit_20, 19, 0, 1, 1)
        self.str_lineedit_29 = QtGui.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(12)
        self.str_lineedit_29.setFont(font)
        self.str_lineedit_29.setObjectName("str_lineedit_29")
        self.gridLayout_2.addWidget(self.str_lineedit_29, 8, 3, 1, 1)
        self.cmd_name_lineedit_12 = QtGui.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(12)
        self.cmd_name_lineedit_12.setFont(font)
        self.cmd_name_lineedit_12.setObjectName("cmd_name_lineedit_12")
        self.gridLayout_2.addWidget(self.cmd_name_lineedit_12, 11, 1, 1, 1)
        self.cmd_name_lineedit_5 = QtGui.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(12)
        self.cmd_name_lineedit_5.setFont(font)
        self.cmd_name_lineedit_5.setObjectName("cmd_name_lineedit_5")
        self.gridLayout_2.addWidget(self.cmd_name_lineedit_5, 4, 1, 1, 1)
        self.cmd_name_lineedit_19 = QtGui.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(12)
        self.cmd_name_lineedit_19.setFont(font)
        self.cmd_name_lineedit_19.setObjectName("cmd_name_lineedit_19")
        self.gridLayout_2.addWidget(self.cmd_name_lineedit_19, 18, 1, 1, 1)
        self.cmd_name_lineedit_31 = QtGui.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(12)
        self.cmd_name_lineedit_31.setFont(font)
        self.cmd_name_lineedit_31.setObjectName("cmd_name_lineedit_31")
        self.gridLayout_2.addWidget(self.cmd_name_lineedit_31, 10, 4, 1, 1)
        self.str_lineedit_12 = QtGui.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(12)
        self.str_lineedit_12.setFont(font)
        self.str_lineedit_12.setObjectName("str_lineedit_12")
        self.gridLayout_2.addWidget(self.str_lineedit_12, 11, 0, 1, 1)
        self.str_lineedit_37 = QtGui.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(12)
        self.str_lineedit_37.setFont(font)
        self.str_lineedit_37.setObjectName("str_lineedit_37")
        self.gridLayout_2.addWidget(self.str_lineedit_37, 16, 3, 1, 1)
        self.str_lineedit_21 = QtGui.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(12)
        self.str_lineedit_21.setFont(font)
        self.str_lineedit_21.setObjectName("str_lineedit_21")
        self.gridLayout_2.addWidget(self.str_lineedit_21, 0, 3, 1, 1)
        self.str_lineedit_30 = QtGui.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(12)
        self.str_lineedit_30.setFont(font)
        self.str_lineedit_30.setObjectName("str_lineedit_30")
        self.gridLayout_2.addWidget(self.str_lineedit_30, 9, 3, 1, 1)
        self.cmd_name_lineedit_6 = QtGui.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(12)
        self.cmd_name_lineedit_6.setFont(font)
        self.cmd_name_lineedit_6.setObjectName("cmd_name_lineedit_6")
        self.gridLayout_2.addWidget(self.cmd_name_lineedit_6, 5, 1, 1, 1)
        self.cmd_name_lineedit_20 = QtGui.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(12)
        self.cmd_name_lineedit_20.setFont(font)
        self.cmd_name_lineedit_20.setObjectName("cmd_name_lineedit_20")
        self.gridLayout_2.addWidget(self.cmd_name_lineedit_20, 19, 1, 1, 1)
        self.cmd_name_lineedit_36 = QtGui.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(12)
        self.cmd_name_lineedit_36.setFont(font)
        self.cmd_name_lineedit_36.setObjectName("cmd_name_lineedit_36")
        self.gridLayout_2.addWidget(self.cmd_name_lineedit_36, 15, 4, 1, 1)
        self.cmd_name_lineedit_13 = QtGui.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(12)
        self.cmd_name_lineedit_13.setFont(font)
        self.cmd_name_lineedit_13.setObjectName("cmd_name_lineedit_13")
        self.gridLayout_2.addWidget(self.cmd_name_lineedit_13, 12, 1, 1, 1)
        self.str_lineedit_2 = QtGui.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(12)
        self.str_lineedit_2.setFont(font)
        self.str_lineedit_2.setObjectName("str_lineedit_2")
        self.gridLayout_2.addWidget(self.str_lineedit_2, 1, 0, 1, 1)
        self.cmd_name_lineedit_26 = QtGui.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(12)
        self.cmd_name_lineedit_26.setFont(font)
        self.cmd_name_lineedit_26.setObjectName("cmd_name_lineedit_26")
        self.gridLayout_2.addWidget(self.cmd_name_lineedit_26, 5, 4, 1, 1)
        self.str_lineedit_13 = QtGui.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(12)
        self.str_lineedit_13.setFont(font)
        self.str_lineedit_13.setObjectName("str_lineedit_13")
        self.gridLayout_2.addWidget(self.str_lineedit_13, 12, 0, 1, 1)
        self.str_lineedit_38 = QtGui.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(12)
        self.str_lineedit_38.setFont(font)
        self.str_lineedit_38.setObjectName("str_lineedit_38")
        self.gridLayout_2.addWidget(self.str_lineedit_38, 17, 3, 1, 1)
        self.str_lineedit_22 = QtGui.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(12)
        self.str_lineedit_22.setFont(font)
        self.str_lineedit_22.setObjectName("str_lineedit_22")
        self.gridLayout_2.addWidget(self.str_lineedit_22, 1, 3, 1, 1)
        self.str_lineedit_31 = QtGui.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(12)
        self.str_lineedit_31.setFont(font)
        self.str_lineedit_31.setObjectName("str_lineedit_31")
        self.gridLayout_2.addWidget(self.str_lineedit_31, 10, 3, 1, 1)
        self.str_lineedit_3 = QtGui.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(12)
        self.str_lineedit_3.setFont(font)
        self.str_lineedit_3.setObjectName("str_lineedit_3")
        self.gridLayout_2.addWidget(self.str_lineedit_3, 2, 0, 1, 1)
        self.cmd_name_lineedit_32 = QtGui.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(12)
        self.cmd_name_lineedit_32.setFont(font)
        self.cmd_name_lineedit_32.setObjectName("cmd_name_lineedit_32")
        self.gridLayout_2.addWidget(self.cmd_name_lineedit_32, 11, 4, 1, 1)
        self.cmd_name_lineedit_7 = QtGui.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(12)
        self.cmd_name_lineedit_7.setFont(font)
        self.cmd_name_lineedit_7.setObjectName("cmd_name_lineedit_7")
        self.gridLayout_2.addWidget(self.cmd_name_lineedit_7, 6, 1, 1, 1)
        self.cmd_name_lineedit_14 = QtGui.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(12)
        self.cmd_name_lineedit_14.setFont(font)
        self.cmd_name_lineedit_14.setObjectName("cmd_name_lineedit_14")
        self.gridLayout_2.addWidget(self.cmd_name_lineedit_14, 13, 1, 1, 1)
        self.str_lineedit_14 = QtGui.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(12)
        self.str_lineedit_14.setFont(font)
        self.str_lineedit_14.setObjectName("str_lineedit_14")
        self.gridLayout_2.addWidget(self.str_lineedit_14, 13, 0, 1, 1)
        self.cmd_name_lineedit_27 = QtGui.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(12)
        self.cmd_name_lineedit_27.setFont(font)
        self.cmd_name_lineedit_27.setObjectName("cmd_name_lineedit_27")
        self.gridLayout_2.addWidget(self.cmd_name_lineedit_27, 6, 4, 1, 1)
        self.cmd_name_lineedit_21 = QtGui.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(12)
        self.cmd_name_lineedit_21.setFont(font)
        self.cmd_name_lineedit_21.setObjectName("cmd_name_lineedit_21")
        self.gridLayout_2.addWidget(self.cmd_name_lineedit_21, 0, 4, 1, 1)
        self.str_lineedit_23 = QtGui.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(12)
        self.str_lineedit_23.setFont(font)
        self.str_lineedit_23.setObjectName("str_lineedit_23")
        self.gridLayout_2.addWidget(self.str_lineedit_23, 2, 3, 1, 1)
        self.str_lineedit_4 = QtGui.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(12)
        self.str_lineedit_4.setFont(font)
        self.str_lineedit_4.setObjectName("str_lineedit_4")
        self.gridLayout_2.addWidget(self.str_lineedit_4, 3, 0, 1, 1)
        self.str_lineedit_39 = QtGui.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(12)
        self.str_lineedit_39.setFont(font)
        self.str_lineedit_39.setObjectName("str_lineedit_39")
        self.gridLayout_2.addWidget(self.str_lineedit_39, 18, 3, 1, 1)
        self.cmd_name_lineedit_37 = QtGui.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(12)
        self.cmd_name_lineedit_37.setFont(font)
        self.cmd_name_lineedit_37.setObjectName("cmd_name_lineedit_37")
        self.gridLayout_2.addWidget(self.cmd_name_lineedit_37, 16, 4, 1, 1)
        self.str_lineedit_32 = QtGui.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(12)
        self.str_lineedit_32.setFont(font)
        self.str_lineedit_32.setObjectName("str_lineedit_32")
        self.gridLayout_2.addWidget(self.str_lineedit_32, 11, 3, 1, 1)
        self.str_lineedit_15 = QtGui.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(12)
        self.str_lineedit_15.setFont(font)
        self.str_lineedit_15.setObjectName("str_lineedit_15")
        self.gridLayout_2.addWidget(self.str_lineedit_15, 14, 0, 1, 1)
        self.cmd_name_lineedit_8 = QtGui.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(12)
        self.cmd_name_lineedit_8.setFont(font)
        self.cmd_name_lineedit_8.setObjectName("cmd_name_lineedit_8")
        self.gridLayout_2.addWidget(self.cmd_name_lineedit_8, 7, 1, 1, 1)
        self.str_lineedit_5 = QtGui.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(12)
        self.str_lineedit_5.setFont(font)
        self.str_lineedit_5.setObjectName("str_lineedit_5")
        self.gridLayout_2.addWidget(self.str_lineedit_5, 4, 0, 1, 1)
        self.cmd_name_lineedit_15 = QtGui.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(12)
        self.cmd_name_lineedit_15.setFont(font)
        self.cmd_name_lineedit_15.setObjectName("cmd_name_lineedit_15")
        self.gridLayout_2.addWidget(self.cmd_name_lineedit_15, 14, 1, 1, 1)
        self.cmd_name_lineedit_1 = QtGui.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(12)
        self.cmd_name_lineedit_1.setFont(font)
        self.cmd_name_lineedit_1.setObjectName("cmd_name_lineedit_1")
        self.gridLayout_2.addWidget(self.cmd_name_lineedit_1, 0, 1, 1, 1)
        self.str_lineedit_24 = QtGui.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(12)
        self.str_lineedit_24.setFont(font)
        self.str_lineedit_24.setObjectName("str_lineedit_24")
        self.gridLayout_2.addWidget(self.str_lineedit_24, 3, 3, 1, 1)
        self.str_lineedit_40 = QtGui.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(12)
        self.str_lineedit_40.setFont(font)
        self.str_lineedit_40.setObjectName("str_lineedit_40")
        self.gridLayout_2.addWidget(self.str_lineedit_40, 19, 3, 1, 1)
        self.str_lineedit_33 = QtGui.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(12)
        self.str_lineedit_33.setFont(font)
        self.str_lineedit_33.setObjectName("str_lineedit_33")
        self.gridLayout_2.addWidget(self.str_lineedit_33, 12, 3, 1, 1)
        self.cmd_name_lineedit_22 = QtGui.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(12)
        self.cmd_name_lineedit_22.setFont(font)
        self.cmd_name_lineedit_22.setObjectName("cmd_name_lineedit_22")
        self.gridLayout_2.addWidget(self.cmd_name_lineedit_22, 1, 4, 1, 1)
        self.cmd_name_lineedit_28 = QtGui.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(12)
        self.cmd_name_lineedit_28.setFont(font)
        self.cmd_name_lineedit_28.setObjectName("cmd_name_lineedit_28")
        self.gridLayout_2.addWidget(self.cmd_name_lineedit_28, 7, 4, 1, 1)
        self.str_lineedit_6 = QtGui.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(12)
        self.str_lineedit_6.setFont(font)
        self.str_lineedit_6.setObjectName("str_lineedit_6")
        self.gridLayout_2.addWidget(self.str_lineedit_6, 5, 0, 1, 1)
        self.cmd_name_lineedit_38 = QtGui.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(12)
        self.cmd_name_lineedit_38.setFont(font)
        self.cmd_name_lineedit_38.setObjectName("cmd_name_lineedit_38")
        self.gridLayout_2.addWidget(self.cmd_name_lineedit_38, 17, 4, 1, 1)
        self.cmd_name_lineedit_40 = QtGui.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(12)
        self.cmd_name_lineedit_40.setFont(font)
        self.cmd_name_lineedit_40.setObjectName("cmd_name_lineedit_40")
        self.gridLayout_2.addWidget(self.cmd_name_lineedit_40, 19, 4, 1, 1)
        self.gridLayout_2.setColumnStretch(0, 2)
        self.gridLayout_2.setColumnStretch(1, 1)
        self.gridLayout_2.setColumnStretch(2, 1)
        self.gridLayout_2.setColumnStretch(3, 2)
        self.gridLayout_2.setColumnStretch(4, 1)
        self.gridLayout_2.setColumnStretch(5, 1)
        self.gridLayout.addWidget(self.frame, 0, 1, 1, 1)

        self.retranslateUi(ScriptSetting)
        QtCore.QMetaObject.connectSlotsByName(ScriptSetting)

    def retranslateUi(self, ScriptSetting):
        ScriptSetting.setWindowTitle(QtGui.QApplication.translate("ScriptSetting", "Setting", None, QtGui.QApplication.UnicodeUTF8))
        self.ok_btn.setText(QtGui.QApplication.translate("ScriptSetting", "OK", None, QtGui.QApplication.UnicodeUTF8))

